/**
 * TRADING QUOTES DATABASE — 500+ motivational quotes
 *
 * Categories: wealth, discipline, consistency, success, patience, freedom, psychology
 * Selection: deterministic round-robin by date+slot — never repeats in < 500 turns.
 */

export type QuoteCategory =
  | "wealth"
  | "discipline"
  | "consistency"
  | "success"
  | "patience"
  | "freedom"
  | "psychology"

export type QuoteEntry = {
  text: string
  author?: string | null
  category: QuoteCategory
}

const QUOTES: QuoteEntry[] = [
  // ── WEALTH ────────────────────────────────────────────
  { text: "The stock market is a device for transferring money from the impatient to the patient.", author: "Warren Buffett", category: "wealth" },
  { text: "Wealth is the ability to fully experience life.", author: "Henry David Thoreau", category: "wealth" },
  { text: "The real key to making money in stocks is not to get scared out of them.", author: "Peter Lynch", category: "wealth" },
  { text: "It's not how much money you make, but how much money you keep.", author: "Robert Kiyosaki", category: "wealth" },
  { text: "Opportunities come infrequently. When it rains gold, put out the bucket, not the thimble.", author: "Warren Buffett", category: "wealth" },
  { text: "The most important quality for an investor is temperament, not intellect.", author: "Warren Buffett", category: "wealth" },
  { text: "Wealth consists not in having great possessions, but in having few wants.", author: "Epictetus", category: "wealth" },
  { text: "The goal isn't more money. The goal is living life on your terms.", author: null, category: "wealth" },
  { text: "Every trade is a brick in the cathedral of your financial freedom.", author: null, category: "wealth" },
  { text: "Wealth is what you don't see. It's the assets you build while others sleep.", author: null, category: "wealth" },
  { text: "Don't work for money; make money work for you.", author: "Robert Kiyosaki", category: "wealth" },
  { text: "The rich invest in time, the poor invest in money.", author: null, category: "wealth" },
  { text: "Financial freedom is available to those who learn about it and work for it.", author: "Robert Kiyosaki", category: "wealth" },
  { text: "The best investment you can make is in yourself.", author: "Warren Buffett", category: "wealth" },
  { text: "Investing should be more like watching paint dry or watching grass grow.", author: "Paul Samuelson", category: "wealth" },
  { text: "The four most dangerous words in investing are: 'This time it's different.'", author: "John Templeton", category: "wealth" },
  { text: "Wide diversification is only required when investors do not understand what they are doing.", author: "Warren Buffett", category: "wealth" },
  { text: "Risk comes from not knowing what you're doing.", author: "Warren Buffett", category: "wealth" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb", category: "wealth" },
  { text: "Money grows on the tree of patience.", author: null, category: "wealth" },

  // ── DISCIPLINE ─────────────────────────────────────────
  { text: "The market rewards discipline, not emotion. Every signal is an opportunity, but consistency creates wealth.", author: null, category: "discipline" },
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn", category: "discipline" },
  { text: "Without discipline, no trading system will work. With discipline, any system can work.", author: null, category: "discipline" },
  { text: "The markets are a test of character. Stay disciplined, stay focused.", author: null, category: "discipline" },
  { text: "Plan your trade and trade your plan.", author: null, category: "discipline" },
  { text: "Emotions are your enemy in the market. Logic and discipline are your shield.", author: null, category: "discipline" },
  { text: "Success in trading comes from controlling your emotions, not predicting the market.", author: null, category: "discipline" },
  { text: "The difference between a successful trader and a failure is the ability to follow their rules.", author: null, category: "discipline" },
  { text: "Trading is not about being right. It's about being disciplined.", author: null, category: "discipline" },
  { text: "Discipline means choosing between what you want now and what you want most.", author: null, category: "discipline" },
  { text: "A disciplined trader never chases the market. They let the market come to them.", author: null, category: "discipline" },
  { text: "The key to trading success is emotional discipline. If intelligence were the key, everyone would be rich.", author: "Victor Sperandeo", category: "discipline" },
  { text: "Trading is a journey of self-discipline. Master yourself before you master the market.", author: null, category: "discipline" },
  { text: "The best traders have no ego. They follow the system, not their feelings.", author: null, category: "discipline" },
  { text: "Discipline is doing what needs to be done, even if you don't want to do it.", author: null, category: "discipline" },
  { text: "In trading, patience is not passive. It is active discipline.", author: null, category: "discipline" },
  { text: "Your trading plan is your map. Discipline is the compass.", author: null, category: "discipline" },
  { text: "The goal is not to be right. The goal is to be profitable with discipline.", author: null, category: "discipline" },
  { text: "Losing trades are part of the game. Losing discipline is not.", author: null, category: "discipline" },
  { text: "Trading without discipline is like driving without brakes.", author: null, category: "discipline" },

  // ── CONSISTENCY ────────────────────────────────────────
  { text: "Success is not built from one trade. It is built from hundreds of disciplined decisions.", author: null, category: "consistency" },
  { text: "Small consistent gains compound into extraordinary wealth over time.", author: null, category: "consistency" },
  { text: "It's not about the size of your wins. It's about the consistency of your process.", author: null, category: "consistency" },
  { text: "The market rewards consistency over intensity.", author: null, category: "consistency" },
  { text: "Rome wasn't built in a day, and neither is a trading fortune. Stay consistent.", author: null, category: "consistency" },
  { text: "Compounding is the eighth wonder of the world. Consistency fuels compounding.", author: null, category: "consistency" },
  { text: "Be consistent, not perfect. Perfect is the enemy of profitable.", author: null, category: "consistency" },
  { text: "Trading is a marathon, not a sprint. Consistency wins the race.", author: null, category: "consistency" },
  { text: "The secret to success is consistency of purpose.", author: "Benjamin Disraeli", category: "consistency" },
  { text: "Success is the product of daily habits, not once-in-a-lifetime transformations.", author: "James Clear", category: "consistency" },
  { text: "Consistent small wins build unshakeable confidence.", author: null, category: "consistency" },
  { text: "The most powerful force in trading is consistent execution of a sound strategy.", author: null, category: "consistency" },
  { text: "You don't need to be great to start, but you need to start to be great consistently.", author: null, category: "consistency" },
  { text: "Consistency is what transforms average into excellence.", author: null, category: "consistency" },
  { text: "Show up every day. The market rewards presence, not absence.", author: null, category: "consistency" },
  { text: "A small leak will sink a great ship. Consistent discipline prevents leaks.", author: null, category: "consistency" },
  { text: "The distance between dreams and reality is consistent action.", author: null, category: "consistency" },
  { text: "Trading consistency is not about never losing. It's about winning over time.", author: null, category: "consistency" },
  { text: "Build systems, not goals. Systems produce consistent results.", author: null, category: "consistency" },
  { text: "Consistent effort, not strength or intelligence, is the key to unlocking our potential.", author: null, category: "consistency" },

  // ── SUCCESS ────────────────────────────────────────────
  { text: "Every successful trader was once a beginner who refused to quit.", author: null, category: "success" },
  { text: "Success is not final, failure is not fatal. It is the courage to continue that counts.", author: "Winston Churchill", category: "success" },
  { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt", category: "success" },
  { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau", category: "success" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain", category: "success" },
  { text: "Don't let what you cannot do interfere with what you can do.", author: "John Wooden", category: "success" },
  { text: "Success is not in what you have, but who you become.", author: null, category: "success" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney", category: "success" },
  { text: "Successful people do what unsuccessful people are not willing to do.", author: null, category: "success" },
  { text: "Your attitude, not your aptitude, determines your altitude.", author: "Zig Ziglar", category: "success" },
  { text: "Success is the sum of small efforts repeated day in and day out.", author: "Robert Collier", category: "success" },
  { text: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon", category: "success" },
  { text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett", category: "success" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt", category: "success" },
  { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill", category: "success" },
  { text: "The road to success and the road to failure are almost exactly the same.", author: "Colin R. Davis", category: "success" },
  { text: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer", category: "success" },
  { text: "The successful warrior is the average man with laser-like focus.", author: "Bruce Lee", category: "success" },
  { text: "Success demands singleness of purpose.", author: "Vince Lombardi", category: "success" },
  { text: "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.", author: "Colin Powell", category: "success" },

  // ── PATIENCE ───────────────────────────────────────────
  { text: "Markets never sleep. Neither should your patience.", author: null, category: "patience" },
  { text: "Patience is not the ability to wait, but the ability to keep a good attitude while waiting.", author: null, category: "patience" },
  { text: "The stock market is a device for transferring money from the impatient to the patient.", author: "Warren Buffett", category: "patience" },
  { text: "Patience is the key to paradise.", author: "Turkish Proverb", category: "patience" },
  { text: "He that can have patience can have what he will.", author: "Benjamin Franklin", category: "patience" },
  { text: "Patience is bitter, but its fruit is sweet.", author: "Aristotle", category: "patience" },
  { text: "One minute of patience, ten years of peace.", author: "Greek Proverb", category: "patience" },
  { text: "The two most powerful warriors are patience and time.", author: "Leo Tolstoy", category: "patience" },
  { text: "Patience and perseverance have a magical effect before which difficulties disappear.", author: "John Quincy Adams", category: "patience" },
  { text: "Have patience. All things are difficult before they become easy.", author: "Saadi", category: "patience" },
  { text: "Patience is not passive; it is concentrated strength.", author: "Bruce Lee", category: "patience" },
  { text: "The key to everything is patience. You get the chicken by hatching the egg, not by smashing it.", author: "Arnold Glasow", category: "patience" },
  { text: "Patience is the calm acceptance that things can happen in a different order than you have in mind.", author: null, category: "patience" },
  { text: "In trading, patience is a competitive advantage.", author: null, category: "patience" },
  { text: "Wait for the right opportunity. Patience prevents losses.", author: null, category: "patience" },
  { text: "The greatest trader is not the one who makes the most trades, but the one who waits for the best ones.", author: null, category: "patience" },
  { text: "Patience is the art of hoping.", author: "Luc de Clapiers", category: "patience" },
  { text: "Rivers know this: there is no hurry. We shall get there someday.", author: "Winnie the Pooh", category: "patience" },
  { text: "Adopt the pace of nature: her secret is patience.", author: "Ralph Waldo Emerson", category: "patience" },
  { text: "Patience is the foundation of peaceful trading.", author: null, category: "patience" },

  // ── FREEDOM ────────────────────────────────────────────
  { text: "Financial freedom is not a destination. It's a mindset.", author: null, category: "freedom" },
  { text: "The goal is not to be rich. The goal is to be free.", author: null, category: "freedom" },
  { text: "Money is a tool. Freedom is the goal.", author: null, category: "freedom" },
  { text: "True freedom is having enough to live life on your own terms.", author: null, category: "freedom" },
  { text: "Financial independence is the ability to live life without being chained to a paycheck.", author: null, category: "freedom" },
  { text: "The greatest wealth is the freedom to choose how you spend your time.", author: null, category: "freedom" },
  { text: "Money can't buy happiness, but it can buy freedom, and freedom brings happiness.", author: null, category: "freedom" },
  { text: "Every trade brings you one step closer to financial sovereignty.", author: null, category: "freedom" },
  { text: "Freedom is not being a slave to your circumstances.", author: null, category: "freedom" },
  { text: "The chains of habit are too weak to be felt until they are too strong to be broken.", author: "Samuel Johnson", category: "freedom" },
  { text: "Financial freedom is the byproduct of disciplined trading.", author: null, category: "freedom" },
  { text: "The price of freedom is eternal vigilance in the markets.", author: null, category: "freedom" },
  { text: "Trade not for money. Trade for the freedom money provides.", author: null, category: "freedom" },
  { text: "The first step toward freedom is the decision to take control of your finances.", author: null, category: "freedom" },
  { text: "Freedom is the oxygen of the soul. Trading is the path to breathe it.", author: null, category: "freedom" },
  { text: "Your capital is your soldier. Deploy it wisely and it will secure your freedom.", author: null, category: "freedom" },
  { text: "The greatest gift of financial independence is options.", author: null, category: "freedom" },
  { text: "Freedom is not given. It is earned one trade at a time.", author: null, category: "freedom" },
  { text: "Being free means never having to say 'I can't afford it.'", author: null, category: "freedom" },
  { text: "Financial freedom is the foundation upon which all other freedoms are built.", author: null, category: "freedom" },

  // ── PSYCHOLOGY ─────────────────────────────────────────
  { text: "The market is a reflection of human psychology. Understand it, and you understand the market.", author: null, category: "psychology" },
  { text: "Fear and greed are the two strongest emotions in trading. Master them or they will master you.", author: null, category: "psychology" },
  { text: "The biggest risk in trading is not market volatility, but your own psychology.", author: null, category: "psychology" },
  { text: "When everyone is greedy, be fearful. When everyone is fearful, be greedy.", author: "Warren Buffett", category: "psychology" },
  { text: "The most important thing in trading is to keep your losses small and your psychology strong.", author: null, category: "psychology" },
  { text: "Your mind is your most powerful trading tool. Keep it sharp.", author: null, category: "psychology" },
  { text: "The market will test your patience, your discipline, and your resolve. Stay strong.", author: null, category: "psychology" },
  { text: "Losses are inevitable. How you react to them determines your success.", author: null, category: "psychology" },
  { text: "The goal is not to avoid losses, but to manage them intelligently.", author: null, category: "psychology" },
  { text: "Winning in trading is 80% psychology and 20% strategy.", author: null, category: "psychology" },
  { text: "The greatest enemy of a trader is not the market, but their own emotions.", author: null, category: "psychology" },
  { text: "Fear of missing out (FOMO) has destroyed more portfolios than bear markets.", author: null, category: "psychology" },
  { text: "Stay calm. Stay focused. The market rewards the patient mind.", author: null, category: "psychology" },
  { text: "Your trading journal is a mirror of your psychology. Study it.", author: null, category: "psychology" },
  { text: "The market does not care about your opinion. It only cares about your discipline.", author: null, category: "psychology" },
  { text: "Revenge trading is the fastest way to destroy your account.", author: null, category: "psychology" },
  { text: "Learn to love the process, not the outcome. The outcome will follow.", author: null, category: "psychology" },
  { text: "The only easy day was yesterday. Every day in the market is a new challenge.", author: null, category: "psychology" },
  { text: "Mental toughness separates professional traders from amateurs.", author: null, category: "psychology" },
  { text: "Your mindset determines your market set. Change your mind, change your results.", author: null, category: "psychology" },

  // ── EXTRA: Trading Wisdom ──────────────────────────────
  { text: "The trend is your friend until the end when it bends.", author: null, category: "discipline" },
  { text: "Don't catch a falling knife. Wait for confirmation.", author: null, category: "discipline" },
  { text: "The first loss is the best loss. Cut losses quickly.", author: null, category: "discipline" },
  { text: "Let your profits run. Cut your losses short.", author: null, category: "discipline" },
  { text: "Never add to a losing position.", author: null, category: "discipline" },
  { text: "The market can remain irrational longer than you can remain solvent.", author: "John Maynard Keynes", category: "psychology" },
  { text: "Buy on rumors, sell on news.", author: null, category: "psychology" },
  { text: "The most dangerous phrase in the language is 'we've always done it this way.'", author: "Grace Hopper", category: "success" },
  { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein", category: "success" },
  { text: "It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change.", author: "Charles Darwin", category: "success" },
  { text: "The best way to predict the future is to create it.", author: "Peter Drucker", category: "success" },
  { text: "Do not wait to strike till the iron is hot, but make it hot by striking.", author: "William Butler Yeats", category: "success" },
  { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford", category: "success" },
  { text: "In the world of trading, he who masters the art of patience controls the game.", author: null, category: "patience" },
  { text: "A winner is just a loser who tried one more time.", author: null, category: "consistency" },
  { text: "The expert in anything was once a beginner.", author: null, category: "success" },
  { text: "Your biggest competition is your own doubt. Silence it and trade.", author: null, category: "psychology" },
  { text: "Champions keep playing until they get it right.", author: "Billie Jean King", category: "consistency" },
  { text: "The only limit to your impact is your imagination and commitment.", author: "Tony Robbins", category: "success" },
  { text: "The secret of success is to do the common thing uncommonly well.", author: "John D. Rockefeller", category: "consistency" },
  { text: "Don't count the days, make the days count.", author: "Muhammad Ali", category: "success" },
  { text: "The harder you work, the luckier you get.", author: "Gary Player", category: "success" },
  { text: "Success is not the result of spontaneous combustion. You must set yourself on fire.", author: "Arnold Glasow", category: "success" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson", category: "success" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson", category: "psychology" },
  { text: "In trading, as in life, the only way out is through.", author: null, category: "psychology" },
  { text: "Trading is simple, but not easy. The discipline is hard, but the rewards are worth it.", author: null, category: "discipline" },
  { text: "Don't trade to get rich. Trade to be free.", author: null, category: "freedom" },
  { text: "Every master was once a disaster. Keep going.", author: null, category: "consistency" },
  { text: "The best time to start trading was years ago. The second best time is today.", author: null, category: "success" },
  { text: "A smooth sea never made a skilled sailor. A calm market never made a great trader.", author: null, category: "psychology" },
  { text: "The ocean of opportunity is vast. Cast your net with patience and discipline.", author: null, category: "patience" },
  { text: "Stars cannot shine without darkness. Markets cannot reward without volatility.", author: null, category: "psychology" },
  { text: "The phoenix rises from the ashes. After every loss comes the opportunity for rebirth.", author: null, category: "psychology" },
  { text: "Trees grow tall in storms. Traders grow strong in volatile markets.", author: null, category: "psychology" },
  { text: "The river cuts through rock not because of its power, but because of its persistence.", author: null, category: "consistency" },
  { text: "Mountains are climbed one step at a time. Fortunes are built one trade at a time.", author: null, category: "consistency" },
  { text: "The eagle does not chase flies. Wait for the right opportunity.", author: null, category: "patience" },
  { text: "The lion hunts with patience, not speed. Be the lion.", author: null, category: "patience" },
  { text: "A garden does not grow overnight. Neither does a portfolio.", author: null, category: "patience" },
  { text: "The seed of wealth is planted with discipline and watered with patience.", author: null, category: "wealth" },
  { text: "Turn your wounds into wisdom. Turn your losses into lessons.", author: null, category: "psychology" },
  { text: "The market is a classroom, and every trade is a lesson. Never stop learning.", author: null, category: "psychology" },
  { text: "Your past trades do not define you. Your next trade is a fresh opportunity.", author: null, category: "psychology" },
  { text: "Be the trader who says 'I can' instead of 'I might.'", author: null, category: "success" },
  { text: "The difference between a dream and a goal is a deadline. Set yours today.", author: null, category: "success" },
  { text: "Fortune favors the bold, but the bold must also be disciplined.", author: null, category: "discipline" },
  { text: "A ship in harbor is safe, but that is not what ships are built for.", author: "John A. Shedd", category: "success" },
  { text: "Take calculated risks. That is quite different from being rash.", author: "George S. Patton", category: "discipline" },
  { text: "The biggest adventure you can take is to live the life of your dreams.", author: "Oprah Winfrey", category: "freedom" },
  { text: "The secret of getting ahead is getting started. The secret of getting started is breaking complex tasks into small manageable steps.", author: "Mark Twain", category: "consistency" },
  { text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett", category: "success" },
  { text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar", category: "success" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins", category: "success" },
  { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair", category: "psychology" },
  { text: "The best revenge is massive success.", author: "Frank Sinatra", category: "success" },
  { text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson", category: "consistency" },
  { text: "There is no substitute for hard work.", author: "Thomas Edison", category: "consistency" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs", category: "success" },
  { text: "Stay hungry, stay foolish.", author: "Steve Jobs", category: "success" },
  { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs", category: "success" },
  { text: "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.", author: "Steve Jobs", category: "success" },
  { text: "Quality is more important than quantity. One home run is much better than two doubles.", author: "Steve Jobs", category: "discipline" },
  { text: "Sometimes life is going to hit you in the head with a brick. Don't lose faith.", author: "Steve Jobs", category: "psychology" },
  { text: "Have the courage to follow your heart and intuition. They somehow already know what you truly want to become.", author: "Steve Jobs", category: "psychology" },
  { text: "The people who are crazy enough to think they can change the world are the ones who do.", author: "Steve Jobs", category: "success" },
  { text: "Details matter. It's worth waiting to get it right.", author: "Steve Jobs", category: "patience" },
  { text: "Design is not just what it looks like and feels like. Design is how it works.", author: "Steve Jobs", category: "success" },
  { text: "There's a guy in a garage who will beat you if you're not careful.", author: "Steve Jobs", category: "consistency" },
  { text: "The ones who are crazy enough to think they can change the world, usually do.", author: null, category: "success" },
  { text: "Believing in yourself is the first step to achieving anything great.", author: null, category: "psychology" },
  { text: "Dream big, work hard, and make it happen.", author: null, category: "success" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt", category: "success" },
  { text: "Great minds discuss ideas. Average minds discuss events. Small minds discuss people.", author: "Eleanor Roosevelt", category: "success" },
  { text: "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate.", author: "Ralph Waldo Emerson", category: "success" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson", category: "psychology" },
  { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson", category: "success" },
  { text: "The only person you should try to be better than is the person you were yesterday.", author: null, category: "consistency" },
  { text: "The best investment you can make is an investment in yourself. The more you learn, the more you earn.", author: "Warren Buffett", category: "wealth" },
  { text: "Price is what you pay. Value is what you get.", author: "Warren Buffett", category: "wealth" },
  { text: "Rule No.1: Never lose money. Rule No.2: Never forget rule No.1.", author: "Warren Buffett", category: "discipline" },
  { text: "It's far better to buy a wonderful company at a fair price than a fair company at a wonderful price.", author: "Warren Buffett", category: "wealth" },
  { text: "It takes 20 years to build a reputation and five minutes to ruin it.", author: "Warren Buffett", category: "discipline" },
  { text: "I will tell you how to become rich. Close the doors. Be fearful when others are greedy.", author: "Warren Buffett", category: "psychology" },
  { text: "Someone's sitting in the shade today because someone planted a tree a long time ago.", author: "Warren Buffett", category: "patience" },
  { text: "If you aren't thinking about owning a stock for 10 years, don't even think about owning it for 10 minutes.", author: "Warren Buffett", category: "patience" },
  { text: "You don't need to be a rocket scientist. Investing is not a game where the guy with the 160 IQ beats the guy with 130 IQ.", author: "Warren Buffett", category: "psychology" },
  { text: "The most important investment you can make is in yourself.", author: "Warren Buffett", category: "wealth" },
  { text: "Buy when everyone else is selling and hold until everyone else is buying.", author: null, category: "psychology" },
  { text: "The stock market is filled with individuals who know the price of everything, but the value of nothing.", author: null, category: "wealth" },
  { text: "In trading, the first step is to survive. The second is to thrive.", author: null, category: "discipline" },
  { text: "A loss is not a loss if you learn from it.", author: null, category: "psychology" },
  { text: "The best traders are not the ones who never lose, but the ones who lose the least when they are wrong.", author: null, category: "discipline" },
  { text: "The market is a voting machine in the short term and a weighing machine in the long term.", author: "Benjamin Graham", category: "patience" },
  { text: "The individual investor should act consistently as an investor and not as a speculator.", author: "Benjamin Graham", category: "discipline" },
  { text: "The intelligent investor is a realist who sells to optimists and buys from pessimists.", author: "Benjamin Graham", category: "psychology" },
  { text: "The essence of investment management is the management of risks, not the management of returns.", author: "Benjamin Graham", category: "discipline" },
  { text: "To be successful, you need to have a plan and the discipline to stick to it.", author: null, category: "discipline" },
  { text: "The biggest risk is not taking any risk. In a world that is changing quickly, the only strategy that is guaranteed to fail is not taking risks.", author: "Mark Zuckerberg", category: "success" },
  { text: "The question isn't who is going to let me; it's who is going to stop me.", author: "Ayn Rand", category: "success" },
  { text: "The best time to take a risk is when the reward justifies it, and you can afford to lose.", author: null, category: "discipline" },
  { text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller", category: "success" },
  { text: "I will prepare and someday my chance will come.", author: "Abraham Lincoln", category: "patience" },
  { text: "The best way to predict your future is to create it.", author: "Abraham Lincoln", category: "success" },
  { text: "Give me six hours to chop down a tree and I will spend the first four sharpening the axe.", author: "Abraham Lincoln", category: "discipline" },
  { text: "Things may come to those who wait, but only the things left by those who hustle.", author: "Abraham Lincoln", category: "success" },
  { text: "The best thing about the future is that it comes one day at a time.", author: "Abraham Lincoln", category: "patience" },
  { text: "Discipline is the soul of an army. It makes small numbers formidable, procures success to the weak, and esteem to all.", author: "George Washington", category: "discipline" },
  { text: "Perseverance and spirit have done wonders in all ages.", author: "George Washington", category: "consistency" },
  { text: "Worry is the interest paid by those who borrow trouble.", author: "George Washington", category: "psychology" },
  { text: "Associate with men of good quality if you esteem your own reputation.", author: "George Washington", category: "success" },
  { text: "Be courteous to all, but intimate with few, and let those few be well tried before you give them your confidence.", author: "George Washington", category: "success" },
  { text: "True friendship is a plant of slow growth.", author: "George Washington", category: "patience" },
  { text: "To be prepared for war is one of the most effective means of preserving peace.", author: "George Washington", category: "discipline" },
  { text: "Labor to keep alive in your breast that little spark of celestial fire called conscience.", author: "George Washington", category: "discipline" },
  { text: "The harder the conflict, the greater the triumph.", author: "George Washington", category: "success" },
  { text: "It is better to be alone than in bad company.", author: "George Washington", category: "success" },
  { text: "Ninety-nine percent of the failures come from people who have the habit of making excuses.", author: "George Washington Carver", category: "success" },
  { text: "When you do the common things in life in an uncommon way, you will command the attention of the world.", author: "George Washington Carver", category: "success" },
  { text: "How far you go in life depends on your being tender with the young, compassionate with the aged, sympathetic with the striving, and tolerant of the weak and strong.", author: "George Washington Carver", category: "success" },
  { text: "Education is the key to unlock the golden door of freedom.", author: "George Washington Carver", category: "freedom" },
  { text: "No idea is so outlandish that it should not be considered with a searching but at the same time with a steady eye.", author: "Winston Churchill", category: "success" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill", category: "consistency" },
  { text: "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.", author: "Winston Churchill", category: "psychology" },
  { text: "Courage is what it takes to stand up and speak; courage is also what it takes to sit down and listen.", author: "Winston Churchill", category: "discipline" },
  { text: "Continuous effort, not strength or intelligence, is the key to unlocking our potential.", author: "Winston Churchill", category: "consistency" },
  { text: "Attitude is a little thing that makes a big difference.", author: "Winston Churchill", category: "psychology" },
  { text: "A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty.", author: "Winston Churchill", category: "psychology" },
  { text: "No prediction is safe. The only thing we know for certain is that the market will surprise us.", author: null, category: "psychology" },
  { text: "The markets are a living entity. They breathe fear and exhale greed.", author: null, category: "psychology" },
  { text: "Every candle tells a story. Every trend reveals a truth.", author: null, category: "psychology" },
  { text: "Charts are the footprints of the market's emotions.", author: null, category: "psychology" },
  { text: "Volume speaks louder than price. Listen to what the market is saying.", author: null, category: "discipline" },
  { text: "The market has a way of finding the weakest hands and shaking them out.", author: null, category: "psychology" },
  { text: "In the battle between bulls and bears, discipline is the deciding factor.", author: null, category: "discipline" },
  { text: "Support and resistance are not lines on a chart. They are the battle lines of market psychology.", author: null, category: "psychology" },
  { text: "Breakouts are the market's way of saying: 'I'm ready to move.' Be ready to follow.", author: null, category: "discipline" },
  { text: "The trend is your anchor in the storm of market noise.", author: null, category: "discipline" },
  { text: "Patience in a trend is the superpower of professional traders.", author: null, category: "patience" },
  { text: "The market giveth and the market taketh away. Blessed be the name of the market.", author: null, category: "psychology" },
  { text: "Trading is a transfer of wealth from the impatient to the patient.", author: null, category: "patience" },
  { text: "The more you learn, the more you earn. Invest in knowledge daily.", author: null, category: "wealth" },
  { text: "A trade without a plan is a gamble. A plan without discipline is a fantasy.", author: null, category: "discipline" },
  { text: "Your portfolio is a reflection of your beliefs. Invest accordingly.", author: null, category: "wealth" },
  { text: "The best traders are the best risk managers.", author: null, category: "discipline" },
  { text: "Don't let a winning trade turn into a loser. Protect your profits.", author: null, category: "discipline" },
  { text: "The moment you become comfortable with loss, you become unstoppable.", author: null, category: "psychology" },
  { text: "Fear is a reaction. Courage is a decision. Decide to trade.", author: null, category: "psychology" },
  { text: "Every great achievement starts with the decision to try.", author: null, category: "success" },
  { text: "The only way to discover the limits of the possible is to venture a little way past them.", author: "Arthur C. Clarke", category: "success" },
  { text: "The impossible is often the untried.", author: "Jim Goodwin", category: "success" },
  { text: "Everything you can imagine is real.", author: "Pablo Picasso", category: "success" },
  { text: "The chief enemy of creativity is good sense.", author: "Pablo Picasso", category: "success" },
  { text: "Action is the foundational key to all success.", author: "Pablo Picasso", category: "success" },
  { text: "The meaning of life is to find your gift. The purpose of life is to give it away.", author: "Pablo Picasso", category: "success" },
  { text: "Learn the rules like a pro, so you can break them like an artist.", author: "Pablo Picasso", category: "success" },
  { text: "It took me four years to paint like Raphael, but a lifetime to paint like a child.", author: "Pablo Picasso", category: "patience" },
  { text: "Success is not a matter of mastering subtle, sophisticated theory but of mastering simple, self-evident basics.", author: null, category: "discipline" },
  { text: "Markets are never wrong. Opinions often are.", author: null, category: "discipline" },
  { text: "The trend is your friend until the end when it bends.", author: null, category: "discipline" },
  { text: "In trading, as in life, there is no certainty, only probability.", author: null, category: "psychology" },
  { text: "The best traders are not the ones who make the most money on winning trades, but the ones who lose the least on losing trades.", author: null, category: "discipline" },
  { text: "A market is the combined behavior of thousands of people reacting to information, misinformation, and whim.", author: null, category: "psychology" },
  { text: "The secret to trading is not predicting the future, but managing the present.", author: null, category: "discipline" },
  { text: "Every trade is a hypothesis. Test it, learn from it, and move on.", author: null, category: "psychology" },
  { text: "The market is a perpetual motion machine of fear and greed. Ride it, don't fight it.", author: null, category: "psychology" },
  { text: "Risk management is not about avoiding loss. It's about ensuring you survive to trade another day.", author: null, category: "discipline" },
  { text: "In the end, the market will do what the market will do. Your job is to respond, not react.", author: null, category: "discipline" },
  { text: "The only constant in the market is change. Adapt or fall behind.", author: null, category: "psychology" },
  { text: "A bear market is when you buy low and sell lower. A bull market is when you buy high and sell higher. The key is to survive both.", author: null, category: "psychology" },
  { text: "The four pillars of trading success: discipline, patience, risk management, and continuous learning.", author: null, category: "discipline" },
  { text: "Don't trade to impress anyone. Trade to feed your freedom.", author: null, category: "freedom" },
  { text: "The best trade is the one that aligns with your strategy, not your emotions.", author: null, category: "discipline" },
  { text: "Markets move in cycles. So does human psychology. Master the cycle, master the market.", author: null, category: "psychology" },
  { text: "Patience is not the absence of action. It is the wisdom to act at the right time.", author: null, category: "patience" },
  { text: "The path to wealth is paved with patience, discipline, and continuous learning.", author: null, category: "wealth" },
  { text: "If you want to be a successful trader, first learn to be a disciplined human being.", author: null, category: "discipline" },
  { text: "The market will teach you humility. Accept the lesson and grow.", author: null, category: "psychology" },
  { text: "Trading is not about being right. It's about making money.", author: null, category: "discipline" },
  { text: "The only easy day was yesterday.", author: "Navy SEALs", category: "discipline" },
  { text: "Under pressure, you don't rise to the occasion. You sink to the level of your training.", author: "Navy SEALs", category: "discipline" },
  { text: "Get comfortable being uncomfortable.", author: null, category: "discipline" },
  { text: "Pain is weakness leaving the body.", author: null, category: "psychology" },
  { text: "The only thing necessary for the triumph of evil is for good men to do nothing.", author: "Edmund Burke", category: "discipline" },
  { text: "Nobody can make you feel inferior without your consent.", author: "Eleanor Roosevelt", category: "psychology" },
  { text: "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.", author: "Ralph Waldo Emerson", category: "success" },
  { text: "What you do speaks so loudly that I cannot hear what you say.", author: "Ralph Waldo Emerson", category: "discipline" },
  { text: "Always do what you are afraid to do.", author: "Ralph Waldo Emerson", category: "psychology" },
  { text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson", category: "success" },
  { text: "For every minute you are angry you lose sixty seconds of happiness.", author: "Ralph Waldo Emerson", category: "psychology" },
  { text: "The fox has many tricks. The hedgehog has but one. But that one is worth more than all the tricks of the fox.", author: null, category: "consistency" },
  { text: "Consistency is the hallmark of the average investor. It's also the hallmark of the average millionaire.", author: null, category: "consistency" },
  { text: "The key to wealth is not IQ. It's discipline.", author: null, category: "wealth" },
  { text: "If you can't control your emotions, you can't control your money.", author: null, category: "psychology" },
  { text: "Trading is 10% strategy and 90% psychology. Master your mind.", author: null, category: "psychology" },
  { text: "The best traders have no opinion about the market. They only have a plan.", author: null, category: "discipline" },
  { text: "Letting go of a losing trade is the hardest but most important skill in trading.", author: null, category: "discipline" },
  { text: "The market doesn't care about your feelings. It only cares about your actions.", author: null, category: "psychology" },
  { text: "A loss is a lesson. A lesson is a gain.", author: null, category: "psychology" },
  { text: "The goal of trading is not to predict the future, but to profit from the present.", author: null, category: "discipline" },
  { text: "The only way to be right in the market is to be patient enough to wait for the right opportunity.", author: null, category: "patience" },
  { text: "Don't try to catch every wave. Focus on the ones that fit your strategy.", author: null, category: "discipline" },
  { text: "The market rewards those who respect it.", author: null, category: "discipline" },
  { text: "In trading, the first loss is the best loss.", author: null, category: "discipline" },
  { text: "Don't let a small loss become a big loss. Cut it early.", author: null, category: "discipline" },
  { text: "The difference between a successful trader and a failed one is the ability to control risk.", author: null, category: "discipline" },
  { text: "Trading is not a get-rich-quick scheme. It's a get-rich-slow process.", author: null, category: "patience" },
  { text: "The faster you want to get rich, the faster you'll go broke.", author: null, category: "patience" },
  { text: "Patience is the most important quality in trading. Without it, nothing else matters.", author: null, category: "patience" },
  { text: "The market is a marathon, not a sprint. Pace yourself.", author: null, category: "consistency" },
  { text: "The best traders are the ones who can wait for the perfect setup and then act decisively.", author: null, category: "patience" },
  { text: "Success in trading is not about being a genius. It's about being consistent.", author: null, category: "consistency" },
  { text: "A good trader is not a genius. They are just someone who follows their rules.", author: null, category: "discipline" },
  { text: "The most important thing in trading is to survive. Live to trade another day.", author: null, category: "discipline" },
  { text: "Capital preservation is the first rule of trading. Everything else comes second.", author: null, category: "discipline" },
  { text: "Don't risk what you can't afford to lose. Trade with money you can afford to lose.", author: null, category: "discipline" },
  { text: "The best trades are the ones you don't take. Wait for the right one.", author: null, category: "patience" },
  { text: "The market is full of opportunities. Don't chase them. Let them come to you.", author: null, category: "patience" },
  { text: "In trading, less is more. Fewer trades, better results.", author: null, category: "discipline" },
  { text: "The more you trade, the more you lose. Be selective.", author: null, category: "discipline" },
  { text: "Quality over quantity in everything you do as a trader.", author: null, category: "discipline" },
  { text: "The best traders are not the busiest. They are the most patient.", author: null, category: "patience" },
  { text: "Don't confuse activity with productivity. In trading, patience is productive.", author: null, category: "patience" },
  { text: "The key to trading success is not intelligence but discipline.", author: null, category: "discipline" },
  { text: "You don't need to be a rocket scientist to be a successful trader. You need discipline.", author: null, category: "discipline" },
  { text: "Trading is simple: buy low, sell high. The hard part is the discipline to do it.", author: null, category: "discipline" },
  { text: "The market is the ultimate truth-teller. Listen to it.", author: null, category: "psychology" },
  { text: "Listen to the market, not to your ego.", author: null, category: "psychology" },
  { text: "The market tells you everything you need to know. The question is: are you listening?", author: null, category: "psychology" },
  { text: "Your biggest edge in the market is your discipline. Protect it at all costs.", author: null, category: "discipline" },
  { text: "Discipline is what separates the winners from the dreamers.", author: null, category: "discipline" },
  { text: "Dreams without discipline are just wishes. Wishes don't make money.", author: null, category: "discipline" },
  { text: "Trading is a business. Treat it like one.", author: null, category: "discipline" },
  { text: "Would you open a restaurant without a business plan? Then don't trade without a trading plan.", author: null, category: "discipline" },
  { text: "The most successful traders are the ones who treat trading as a business, not a hobby.", author: null, category: "discipline" },
  { text: "A trading plan without execution is just a wish.", author: null, category: "discipline" },
  { text: "The best trading plan in the world is useless without the discipline to follow it.", author: null, category: "discipline" },
  { text: "You don't need a complex trading system. You need a simple system you can follow consistently.", author: null, category: "consistency" },
  { text: "Simplicity is the ultimate sophistication in trading.", author: null, category: "discipline" },
  { text: "The simplest strategies are often the most profitable.", author: null, category: "discipline" },
  { text: "Keep your strategy simple and your discipline strong.", author: null, category: "discipline" },
  { text: "A simple plan followed consistently beats a complex plan followed sporadically.", author: null, category: "consistency" },
  { text: "The most profitable strategy is the one you stick with.", author: null, category: "consistency" },
  { text: "Consistency beats intensity every time.", author: null, category: "consistency" },
  { text: "The market rewards those who show up every day with discipline and patience.", author: null, category: "discipline" },
  { text: "Be the same trader every day. Consistency builds trust with yourself.", author: null, category: "consistency" },
  { text: "Trust your system. Trust your discipline. Trust the process.", author: null, category: "discipline" },
  { text: "The process is more important than the outcome. Focus on the process.", author: null, category: "discipline" },
  { text: "If you focus on the process, the outcome will take care of itself.", author: null, category: "discipline" },
  { text: "The best traders focus on what they can control: their discipline.", author: null, category: "discipline" },
  { text: "You can't control the market. You can only control your reaction to it.", author: null, category: "psychology" },
  { text: "The only thing you can control in trading is yourself. Master that.", author: null, category: "discipline" },
  { text: "Master yourself and you master the market.", author: null, category: "discipline" },
  { text: "The market is a mirror of your inner state. If you're chaotic, the market will reflect that.", author: null, category: "psychology" },
  { text: "A calm mind is a profitable mind. Stay centered.", author: null, category: "psychology" },
  { text: "The best trades come from a place of calm clarity, not emotional desperation.", author: null, category: "psychology" },
  { text: "Fear and greed are the two sides of the same coin: emotional trading.", author: null, category: "psychology" },
  { text: "The goal is not to eliminate fear and greed, but to manage them.", author: null, category: "psychology" },
  { text: "Awareness of your emotions is the first step to controlling them.", author: null, category: "psychology" },
  { text: "Doubt kills more dreams than failure ever will.", author: null, category: "psychology" },
  { text: "The only thing standing between you and your trading goals is the story you keep telling yourself.", author: null, category: "psychology" },
  { text: "Your beliefs about money shape your trading results. Change your beliefs, change your results.", author: null, category: "psychology" },
  { text: "The moment you accept that losses are part of the game, you become free.", author: null, category: "psychology" },
  { text: "Losses are tuition. Winners are graduation. Keep learning.", author: null, category: "psychology" },
  { text: "Every loss is a lesson. Every lesson makes you a better trader.", author: null, category: "psychology" },
  { text: "The best traders learn more from their losses than from their wins.", author: null, category: "psychology" },
  { text: "If you're not failing, you're not trying hard enough. If you're not learning, you're failing.", author: null, category: "psychology" },
  { text: "There are no failures in trading. Only lessons and feedback.", author: null, category: "psychology" },
  { text: "The difference between a master and a student is that the master has failed more times than the student has tried.", author: null, category: "consistency" },
  { text: "Failure is not the opposite of success. It's part of success.", author: null, category: "success" },
  { text: "The only real failure is the failure to try again.", author: null, category: "consistency" },
  { text: "Fall seven times, stand up eight.", author: "Japanese Proverb", category: "consistency" },
  { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela", category: "consistency" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela", category: "success" },
  { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela", category: "success" },
  { text: "The brave man is not he who does not feel afraid, but he who conquers that fear.", author: "Nelson Mandela", category: "psychology" },
  { text: "After climbing a great hill, one only finds that there are many more hills to climb.", author: "Nelson Mandela", category: "success" },
  { text: "A winner is a dreamer who never gives up.", author: "Nelson Mandela", category: "consistency" },
  { text: "Money won't create success, but the freedom to make more money will.", author: null, category: "freedom" },
  { text: "The secret to wealth is simple: spend less than you earn, invest the difference, and wait.", author: null, category: "wealth" },
  { text: "Financial freedom is not about having money. It's about having choices.", author: null, category: "freedom" },
  { text: "The rich invest in assets. The poor invest in liabilities. The middle class invest in things they think are assets.", author: "Robert Kiyosaki", category: "wealth" },
  { text: "It's not how much money you make. It's how much money you keep and how hard it works for you.", author: "Robert Kiyosaki", category: "wealth" },
  { text: "Financial education is more valuable than money.", author: "Robert Kiyosaki", category: "wealth" },
  { text: "In today's world, the educated are not those with degrees but those with financial literacy.", author: "Robert Kiyosaki", category: "wealth" },
  { text: "The size of your success is measured by the strength of your desire, the size of your dream, and how you handle disappointment along the way.", author: "Robert Kiyosaki", category: "success" },
  { text: "The single most powerful asset we all have is our mind. If it is trained well, it can create enormous wealth.", author: "Robert Kiyosaki", category: "wealth" },
  { text: "Financial freedom is a journey, not a destination. Enjoy the ride.", author: null, category: "freedom" },
  { text: "The first step to financial freedom is taking responsibility for your financial situation.", author: null, category: "freedom" },
  { text: "You can't be free if you're a slave to your finances. Break the chains.", author: null, category: "freedom" },
  { text: "Trading is the vehicle. Financial freedom is the destination. Discipline is the fuel.", author: null, category: "freedom" },
  { text: "Every trade is a vote for the kind of life you want to live. Make it count.", author: null, category: "freedom" },
  { text: "The chains of financial slavery are forged by a lack of financial education.", author: null, category: "freedom" },
  { text: "Knowledge is power. Financial knowledge is freedom.", author: null, category: "freedom" },
  { text: "The best time to start building your financial freedom was yesterday. The next best time is now.", author: null, category: "freedom" },
  { text: "Don't wait for the perfect moment. Take the moment and make it perfect.", author: null, category: "success" },
  { text: "The future depends on what you do today. Not tomorrow. Today.", author: null, category: "consistency" },
  { text: "Your future is created by what you do today, not tomorrow.", author: null, category: "consistency" },
  { text: "The only limit to your success is the one you set in your mind.", author: null, category: "success" },
  { text: "Whether you think you can or think you can't, you're right.", author: "Henry Ford", category: "psychology" },
  { text: "The mind is everything. What you think you become.", author: "Buddha", category: "psychology" },
  { text: "The secret of success is constancy of purpose.", author: "Benjamin Disraeli", category: "consistency" },
  { text: "Action may not always bring happiness, but there is no happiness without action.", author: "Benjamin Disraeli", category: "success" },
  { text: "The greatest good you can do for another is not just share your riches, but reveal to them their own.", author: "Benjamin Disraeli", category: "success" },
  { text: "There is no education like adversity.", author: "Benjamin Disraeli", category: "psychology" },
  { text: "Like all great travellers, I have seen more than I remember, and remember more than I have seen.", author: "Benjamin Disraeli", category: "success" },
  { text: "The secret to success in trading is to eliminate the element of hope.", author: null, category: "discipline" },
  { text: "Hope is not a strategy. The market doesn't care about your hopes.", author: null, category: "discipline" },
  { text: "Trade what you see, not what you think.", author: null, category: "discipline" },
  { text: "The market is the ultimate arbiter of truth. Accept its verdict and move on.", author: null, category: "discipline" },
  { text: "Don't fall in love with a trade. The market will break your heart.", author: null, category: "psychology" },
  { text: "Detachment is the key to clear decision-making in trading.", author: null, category: "psychology" },
  { text: "The best traders are detached from outcomes. They focus on execution.", author: null, category: "discipline" },
  { text: "Be attached to your plan, not to your trades.", author: null, category: "discipline" },
  { text: "The plan is your anchor in the storm of market noise.", author: null, category: "discipline" },
  { text: "Without a plan, you are trading blind. With a plan, you have clarity.", author: null, category: "discipline" },
  { text: "Clarity comes from preparation. Preparation comes from discipline.", author: null, category: "discipline" },
  { text: "The more you prepare, the luckier you get in trading.", author: null, category: "discipline" },
  { text: "Luck is the residue of preparation in trading.", author: null, category: "discipline" },
  { text: "Preparation and discipline are the parents of luck in the markets.", author: null, category: "discipline" },
  { text: "The more you practice, the luckier you become.", author: "Gary Player", category: "consistency" },
  { text: "The harder I practice, the luckier I get.", author: "Gary Player", category: "consistency" },
  { text: "Winners never quit and quitters never win.", author: null, category: "consistency" },
  { text: "If you get tired, learn to rest, not to quit.", author: null, category: "consistency" },
  { text: "The only way to achieve the impossible is to believe it is possible.", author: null, category: "success" },
  { text: "The power of imagination makes us infinite.", author: "John Muir", category: "success" },
  { text: "Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world.", author: "Albert Einstein", category: "success" },
  { text: "Logic will get you from A to B. Imagination will take you everywhere.", author: "Albert Einstein", category: "success" },
  { text: "Learn from yesterday, live for today, hope for tomorrow. The important thing is not to stop questioning.", author: "Albert Einstein", category: "psychology" },
  { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein", category: "success" },
  { text: "The important thing is not to stop questioning. Curiosity has its own reason for existing.", author: "Albert Einstein", category: "success" },
  { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein", category: "psychology" },
  { text: "The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.", author: "Albert Einstein", category: "psychology" },
  { text: "Weakness of attitude becomes weakness of character.", author: "Albert Einstein", category: "psychology" },
  { text: "The only source of knowledge is experience.", author: "Albert Einstein", category: "success" },
  { text: "The value of a man should be seen in what he gives and not in what he is able to receive.", author: "Albert Einstein", category: "success" },
  { text: "Try not to become a man of success, but rather try to become a man of value.", author: "Albert Einstein", category: "success" },
  { text: "Great spirits have always encountered violent opposition from mediocre minds.", author: "Albert Einstein", category: "psychology" },
  { text: "The difference between stupidity and genius is that genius has its limits.", author: "Albert Einstein", category: "psychology" },
  { text: "Anyone who has never made a mistake has never tried anything new.", author: "Albert Einstein", category: "psychology" },
  { text: "Life is like riding a bicycle. To keep your balance, you must keep moving.", author: "Albert Einstein", category: "consistency" },
  { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein", category: "success" },
  { text: "The measure of intelligence is the ability to change.", author: "Albert Einstein", category: "psychology" },
  { text: "Compound interest is the eighth wonder of the world. He who understands it, earns it. He who doesn't, pays it.", author: "Albert Einstein", category: "wealth" },
  { text: "Time is money. Use it wisely.", author: "Benjamin Franklin", category: "wealth" },
  { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin", category: "wealth" },
  { text: "Early to bed and early to rise makes a man healthy, wealthy, and wise.", author: "Benjamin Franklin", category: "discipline" },
  { text: "Well done is better than well said.", author: "Benjamin Franklin", category: "discipline" },
  { text: "Never leave that till tomorrow which you can do today.", author: "Benjamin Franklin", category: "consistency" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin", category: "consistency" },
  { text: "Diligence is the mother of good luck.", author: "Benjamin Franklin", category: "consistency" },
  { text: "There never was a good war or a bad peace.", author: "Benjamin Franklin", category: "success" },
  { text: "We are all born ignorant, but one must work hard to remain stupid.", author: "Benjamin Franklin", category: "success" },
  { text: "A penny saved is a penny earned.", author: "Benjamin Franklin", category: "wealth" },
  { text: "By failing to prepare, you are preparing to fail.", author: "Benjamin Franklin", category: "discipline" },
  { text: "Tell me and I forget, teach me and I may remember, involve me and I learn.", author: "Benjamin Franklin", category: "success" },
  { text: "Without continual growth and progress, such words as improvement, achievement, and success have no meaning.", author: "Benjamin Franklin", category: "success" },
  { text: "Do not anticipate trouble, or worry about what may never happen. Keep in the sunlight.", author: "Benjamin Franklin", category: "psychology" },
  { text: "Success in trading comes from the ability to accept losses and move on.", author: null, category: "psychology" },
  { text: "The best traders think in probabilities, not certainties.", author: null, category: "psychology" },
  { text: "In a world of probabilities, the only certainty is uncertainty. Embrace it.", author: null, category: "psychology" },
  { text: "The market is a game of probabilities. Play the odds, not the outcome.", author: null, category: "discipline" },
  { text: "Think in terms of probability, not possibility.", author: null, category: "psychology" },
  { text: "The best trades have a positive expectancy. Everything else is noise.", author: null, category: "discipline" },
  { text: "If you have an edge, the law of large numbers will work in your favor.", author: null, category: "consistency" },
  { text: "Trust the numbers, not your gut.", author: null, category: "discipline" },
  { text: "The numbers don't lie. Your emotions do.", author: null, category: "discipline" },
  { text: "Data beats emotions. Let the charts speak.", author: null, category: "discipline" },
  { text: "The trend is your friend until the data says otherwise.", author: null, category: "discipline" },
  { text: "Let the data guide your decisions, not your feelings.", author: null, category: "discipline" },
  { text: "In God we trust. All others must bring data.", author: "W. Edwards Deming", category: "discipline" },
  { text: "Without data, you're just another person with an opinion.", author: "W. Edwards Deming", category: "discipline" },
  { text: "Trading without data is like driving with your eyes closed.", author: null, category: "discipline" },
  { text: "The market speaks through price and volume. Learn to listen.", author: null, category: "discipline" },
  { text: "Price is the ultimate indicator. Everything else is derived from it.", author: null, category: "discipline" },
  { text: "Respect the price action above all else.", author: null, category: "discipline" },
  { text: "The only indicator you truly need is price. Everything else is noise.", author: null, category: "discipline" },
  { text: "Strip away the noise. Focus on the price.", author: null, category: "discipline" },
  { text: "Simplicity is the ultimate sophistication in trading.", author: null, category: "discipline" },
  { text: "The most successful traders keep it simple. They don't overcomplicate.", author: null, category: "discipline" },
  { text: "Complication is the enemy of execution.", author: null, category: "discipline" },
  { text: "If you can't explain your strategy simply, you don't understand it well enough.", author: null, category: "discipline" },
  { text: "A simple system, executed with discipline, will outperform a complex system executed poorly.", author: null, category: "consistency" },
  { text: "Master the basics. The advanced stuff is built on the basics.", author: null, category: "discipline" },
  { text: "The fundamentals never go out of style.", author: null, category: "discipline" },
  { text: "Get the fundamentals right and the profits will follow.", author: null, category: "discipline" },
  { text: "There are no shortcuts to success in trading. Master the fundamentals.", author: null, category: "discipline" },
  { text: "The best traders have mastered the basics so well that they can execute them without thinking.", author: null, category: "consistency" },
  { text: "A sure way to lose money is to get fancy. Keep it simple.", author: null, category: "discipline" },
  { text: "Overtrading is the most common cause of failure in trading.", author: null, category: "discipline" },
  { text: "The best thing you can do as a trader is sometimes nothing at all.", author: null, category: "patience" },
  { text: "In trading, doing nothing is a valid strategy.", author: null, category: "patience" },
  { text: "Sometimes the best trade is no trade.", author: null, category: "patience" },
  { text: "Learn to sit on your hands. Patience is a superpower.", author: null, category: "patience" },
  { text: "The ability to wait is the mark of a professional trader.", author: null, category: "patience" },
  { text: "Not every setup is worth taking. Be selective.", author: null, category: "discipline" },
  { text: "The best opportunities are obvious. Don't overthink them.", author: null, category: "discipline" },
  { text: "When the opportunity is clear, act with conviction.", author: null, category: "discipline" },
  { text: "Hesitation kills profits. Be decisive when the time comes.", author: null, category: "discipline" },
  { text: "Analysis paralysis is the enemy of execution.", author: null, category: "discipline" },
  { text: "Know when to act and when to wait. That's the art of trading.", author: null, category: "discipline" },
  { text: "The market will always be there. Don't rush into bad trades.", author: null, category: "patience" },
  { text: "There will always be another opportunity. Don't force it.", author: null, category: "patience" },
  { text: "The market is an endless stream of opportunities. You don't need to catch them all.", author: null, category: "patience" },
  { text: "FOMO is the enemy of good judgment. Stay calm.", author: null, category: "psychology" },
  { text: "Don't let the fear of missing out push you into bad trades.", author: null, category: "psychology" },
  { text: "The trade you don't take is the best trade of the day.", author: null, category: "patience" },
  { text: "If you miss a trade, there will be another one. Don't chase.", author: null, category: "patience" },
  { text: "The market doesn't care if you participated or not. It moves on.", author: null, category: "psychology" },
  { text: "There is no prize for being in every trade. The prize is being in the right trades.", author: null, category: "discipline" },
  { text: "The best traders are the most selective.", author: null, category: "discipline" },
  { text: "Professional traders wait for the best opportunities. Amateurs chase every move.", author: null, category: "patience" },
  { text: "Be the professional. Wait for your pitch.", author: null, category: "patience" },
  { text: "Ted Williams waited for the perfect pitch. You should too.", author: null, category: "patience" },
  { text: "The secret to hitting home runs is waiting for the right pitch.", author: null, category: "patience" },
  { text: "Discipline in trading is the ability to wait for the highest probability setup.", author: null, category: "discipline" },
  { text: "The higher the probability, the more conviction you should have.", author: null, category: "discipline" },
  { text: "Play the high-probability setups and let the low-probability ones go.", author: null, category: "discipline" },
  { text: "In trading, you don't need to be right often. You just need to be right when it counts.", author: null, category: "discipline" },
  { text: "A few big wins can cover many small losses. Focus on the big picture.", author: null, category: "consistency" },
  { text: "The home run trades make the year. Be patient enough to let them come to you.", author: null, category: "patience" },
  { text: "The biggest profits come from the trades you wait the longest for.", author: null, category: "patience" },
  { text: "Patience + Discipline + Risk Management = Trading Success", author: null, category: "discipline" },
  { text: "The formula is simple. Execution is hard. That's why it works.", author: null, category: "discipline" },
  { text: "Everyone wants to be a trader. Few are willing to put in the work.", author: null, category: "success" },
  { text: "The difference between a dreamer and a trader is action.", author: null, category: "success" },
  { text: "Dream big, start small, act now.", author: null, category: "success" },
  { text: "The journey of a thousand miles begins with a single trade.", author: null, category: "success" },
  { text: "The first step is always the hardest. Take it anyway.", author: null, category: "success" },
  { text: "Every expert was once a beginner. Don't be afraid to start.", author: null, category: "success" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar", category: "success" },
  { text: "The only way to do great work is to love what you do. If you haven't found it yet, keep looking.", author: "Steve Jobs", category: "success" },
  { text: "Stay focused, stay disciplined, and never stop learning. The market will reward you.", author: null, category: "discipline" },
  { text: "Your mindset determines your success. Cultivate a winner's mindset.", author: null, category: "psychology" },
  { text: "Winners think about what they want and how to get it. Losers think about what they don't want.", author: null, category: "psychology" },
  { text: "The power of positive thinking is real. Especially in trading.", author: null, category: "psychology" },
  { text: "Visualize success, plan for failure, and execute with discipline.", author: null, category: "discipline" },
  { text: "Hope for the best, plan for the worst, and execute with precision.", author: null, category: "discipline" },
  { text: "Preparation, execution, evaluation. The cycle of continuous improvement.", author: null, category: "discipline" },
  { text: "Review your trades. Learn from your mistakes. Improve every day.", author: null, category: "consistency" },
  { text: "The goal is to be 1% better every day. Compounding improvement leads to mastery.", author: null, category: "consistency" },
  { text: "Small daily improvements over time lead to stunning results.", author: null, category: "consistency" },
  { text: "The best traders are lifelong learners. The market is always changing.", author: null, category: "success" },
  { text: "Adapt or die. The market rewards those who evolve.", author: null, category: "psychology" },
  { text: "The only constant in the market is change. Embrace it.", author: null, category: "psychology" },
  { text: "Be flexible in your thinking but rigid in your discipline.", author: null, category: "discipline" },
  { text: "Adaptability is the key to survival in the markets.", author: null, category: "psychology" },
  { text: "The markets evolve. Your strategy must evolve too.", author: null, category: "discipline" },
  { text: "What worked yesterday may not work tomorrow. Stay curious.", author: null, category: "psychology" },
  { text: "The best traders are perpetual students of the market.", author: null, category: "success" },
  { text: "The more you learn, the more you realize how much you don't know.", author: null, category: "success" },
  { text: "Knowledge compounds like interest. Invest in it daily.", author: null, category: "wealth" },
  { text: "Read. Study. Practice. Repeat. The path to mastery.", author: null, category: "success" },
  { text: "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.", author: "Colin Powell", category: "success" },
  { text: "Perseverance is not a long race; it is many short races one after the other.", author: null, category: "consistency" },
  { text: "Keep going. The market tests your resolve. Don't break.", author: null, category: "consistency" },
  { text: "When the market tests you, remember why you started.", author: null, category: "psychology" },
  { text: "Resilience is the hallmark of a successful trader.", author: null, category: "psychology" },
  { text: "Bend but don't break. Flexibility with discipline is the key.", author: null, category: "discipline" },
  { text: "The market will try to break you. Don't let it.", author: null, category: "psychology" },
  { text: "Your mental health is your most important trading asset. Protect it.", author: null, category: "psychology" },
  { text: "Take breaks. Step away from the screen. Clear your mind.", author: null, category: "psychology" },
  { text: "A fresh perspective can make all the difference in your trading.", author: null, category: "psychology" },
  { text: "Sometimes the best thing you can do is walk away and come back later.", author: null, category: "psychology" },
  { text: "The market will be there when you return. Take care of yourself first.", author: null, category: "psychology" },
  { text: "Trading is a marathon, not a sprint. Pace yourself.", author: null, category: "consistency" },
  { text: "The turtle beats the hare in trading. Slow and steady wins the race.", author: null, category: "consistency" },
  { text: "Consistent small gains over time create massive wealth.", author: null, category: "wealth" },
  { text: "The key to wealth creation is consistency, not intensity.", author: null, category: "wealth" },
  { text: "Slow and steady wins the trading race.", author: null, category: "consistency" },
  { text: "The tortoise beats the hare every time in the markets.", author: null, category: "consistency" },
  { text: "Be the tortoise. Consistent. Patient. Disciplined.", author: null, category: "consistency" },
  { text: "There are no shortcuts to wealth. Only consistent effort over time.", author: null, category: "wealth" },
  { text: "Get rich slow. That's the only way that works.", author: null, category: "wealth" },
  { text: "The best way to get rich quick is to get rich slow.", author: null, category: "patience" },
  { text: "If it sounds too good to be true, it probably is. Stay disciplined.", author: null, category: "discipline" },
  { text: "There are no free lunches in trading. You earn your profits through discipline.", author: null, category: "discipline" },
  { text: "The market doesn't give handouts. You earn every penny through discipline.", author: null, category: "discipline" },
  { text: "Trading is a transfer of wealth from the undisciplined to the disciplined.", author: null, category: "discipline" },
  { text: "Be on the right side of the transfer. Be disciplined.", author: null, category: "discipline" },
]

/**
 * Deterministic quote selection — unique per day + slot, never repeats.
 * With 500+ quotes, this cycles every ~250 days without DB tracking.
 */
export function getDayOfYear(date: Date): number {
  const start = new Date(date.getFullYear(), 0, 0)
  const diff = date.getTime() - start.getTime()
  return Math.floor(diff / (1000 * 60 * 60 * 24))
}

/**
 * Pick a quote for the given date and slot.
 * Deterministic — same date+slot always picks the same quote.
 * No DB tracking needed; cycles through all quotes before repeating.
 */
export function pickQuote(date: Date, slot: "morning" | "evening"): QuoteEntry {
  const dayIndex = getDayOfYear(date)
  const slotOffset = slot === "morning" ? 0 : 1
  const index = (dayIndex * 2 + slotOffset) % QUOTES.length
  return QUOTES[index]
}

/**
 * Get a motivational market insight string for the given slot.
 */
export function buildMarketInsight(date: Date, slot: "morning" | "evening"): string {
  const quote = pickQuote(date, slot)
  const author = quote.author ? ` — ${quote.author}` : ""
  return `"${quote.text}"${author}`
}

/**
 * Build the "Session Result" quote (separate from signal quote to avoid same-day duplication).
 */
export function buildSessionResultQuote(date: Date): string {
  // Use a shifted index so the result quote is different from both morning and evening quotes
  const dayIndex = getDayOfYear(date)
  const index = (dayIndex * 2 + 2) % QUOTES.length
  const quote = QUOTES[index]
  const author = quote.author ? ` — ${quote.author}` : ""
  return `"${quote.text}"${author}`
}

export const QUOTE_COUNT = QUOTES.length
