/** Canonical symbol → CoinGecko id (shared server + client). */
export const COINGECKO_SYMBOL_IDS: Record<string, string> = {
  BTC: "bitcoin",
  ETH: "ethereum",
  SOL: "solana",
  XRP: "ripple",
  ADA: "cardano",
  AVAX: "avalanche-2",
  DOT: "polkadot",
  LINK: "chainlink",
  MATIC: "matic-network",
  DOGE: "dogecoin",
  SHIB: "shiba-inu",
  UNI: "uniswap",
  ATOM: "cosmos",
  LTC: "litecoin",
  BCH: "bitcoin-cash",
  TRX: "tron",
  NEAR: "near",
  APE: "apecoin",
  FTM: "fantom",
  ALGO: "algorand",
  VET: "vechain",
  SAND: "the-sandbox",
  MANA: "decentraland",
  AXS: "axie-infinity",
  GALA: "gala",
  ENJ: "enjincoin",
  CHZ: "chiliz",
  FLOW: "flow",
  HBAR: "hedera-hashgraph",
  XTZ: "tezos",
  THETA: "theta-token",
  EOS: "eos",
  AAVE: "aave",
  MKR: "maker",
  COMP: "compound-governance-token",
  SNX: "havven",
  CRV: "curve-dao-token",
  "1INCH": "1inch",
  YFI: "yearn-finance",
  SUSHI: "sushi",
  BNB: "binancecoin",
}

/** High-visibility symbols always included in resilient live-market catalog. */
export const LIVE_MARKET_CORE_SYMBOLS = [
  "BTC",
  "ETH",
  "SOL",
  "BNB",
  "XRP",
  "ADA",
  "DOGE",
  "AVAX",
  "LINK",
  "DOT",
  "MATIC",
  "LTC",
  "UNI",
  "ATOM",
  "NEAR",
  "APT",
  "ARB",
  "OP",
  "SUI",
  "INJ",
  "FIL",
  "ICP",
  "TRX",
  "SHIB",
  "PEPE",
  "TON",
  "STX",
  "RENDER",
  "FET",
  "IMX",
  "AAVE",
  "MKR",
  "CRV",
  "SNX",
  "SAND",
  "MANA",
] as const
