-- -----------------------------------------------------------------------------
-- Container balance architecture delta
-- Adds 4-layer wallet fields + append-only event ledger for auditability.
-- -----------------------------------------------------------------------------

ALTER TABLE public.user_balances
  ADD COLUMN IF NOT EXISTS active_container_earnings NUMERIC(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS container_withdrawable_earnings NUMERIC(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS lifetime_container_withdrawn NUMERIC(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS lifetime_container_fees NUMERIC(15,2) NOT NULL DEFAULT 0;

COMMENT ON COLUMN public.user_balances.active_container_earnings IS
  'Live in-play profits generated by active container/fixed trades. Never auto-merges to main balance.';
COMMENT ON COLUMN public.user_balances.container_withdrawable_earnings IS
  'Extracted profits after fee from active container earnings; requires explicit transfer_to_main action.';
COMMENT ON COLUMN public.user_balances.lifetime_container_withdrawn IS
  'Gross cumulative extracted amount moved out of active container earnings.';
COMMENT ON COLUMN public.user_balances.lifetime_container_fees IS
  'Cumulative platform fees collected during extraction from active earnings.';

CREATE TABLE IF NOT EXISTS public.container_balance_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL CHECK (event_type IN (
    'deposit_main',
    'fund_trade',
    'earn_active',
    'extract',
    'transfer_to_main',
    'cashout',
    'fee'
  )),
  gross_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
  fee_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
  net_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.container_balance_events
  ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT 'system',
  ADD COLUMN IF NOT EXISTS balance_source TEXT NULL,
  ADD COLUMN IF NOT EXISTS balance_destination TEXT NULL,
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'completed',
  ADD COLUMN IF NOT EXISTS transaction_ref TEXT NULL,
  ADD COLUMN IF NOT EXISTS related_session_id TEXT NULL,
  ADD COLUMN IF NOT EXISTS related_trade_id TEXT NULL,
  ADD COLUMN IF NOT EXISTS related_container_id TEXT NULL,
  ADD COLUMN IF NOT EXISTS actor_type TEXT NOT NULL DEFAULT 'system',
  ADD COLUMN IF NOT EXISTS actor_id TEXT NULL,
  ADD COLUMN IF NOT EXISTS summary TEXT NULL;

CREATE INDEX IF NOT EXISTS container_balance_events_tx_ref_idx
  ON public.container_balance_events (transaction_ref);

CREATE INDEX IF NOT EXISTS container_balance_events_user_created_idx
  ON public.container_balance_events (user_id, created_at DESC);

ALTER TABLE public.container_balance_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own container balance events" ON public.container_balance_events;
CREATE POLICY "Users can view own container balance events"
  ON public.container_balance_events
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);
